spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ""
            clientSecret: ""
          okta:
            client-id: ""
            client-secret: ""
        provider:
          okta:
            authorization-uri: ""
            token-uri: ""
            user-info-uri: ""
            jwk-set-uri: ""
            

logging:
  level:
    root: INFO
    org.springframework.web: TRACE            