spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "your client id"
            clientSecret: "your client secret"
          okta:
            client-id: "your client id"
            client-secret: "your client secret"
        provider:
          okta:
            authorization-uri: https://yourdomain.okta.com/oauth2/default/v1/authorize
            token-uri: https://yourdomain.okta.com/oauth2/default/v1/token
            user-info-uri: https://yourdomain.okta.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://yourdomain.okta.com/oauth2/default/v1/keys
            

logging:
  level:
    root: INFO
    org.springframework.web: TRACE            